version: '3.8'

services:
  # 1. BASE DE DATOS
  db:
    image: postgres:15-alpine
    container_name: global_dashboard_db_pro
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "0102"
      POSTGRES_DB: GLOBAL_INFO
    ports:
      - "5434:5432" 
    volumes:
      - pgdata_pro:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d GLOBAL_INFO"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. BACKEND API
  backend:
    build: ./backend
    container_name: global_dashboard_api_pro
    restart: always
    ports:
      - "8010:8010"
    environment:
      - DATABASE_URL=postgresql://admin:0102@db:5432/GLOBAL_INFO?schema=public
      - JWT_SECRET=super_secreto_cambiar_esto_en_vps
      - NODE_ENV=production
      - PORT=8010
      
      # CORS: Permitir conexiones desde tu frontend en la IP pública
      - FRONTEND_URL=http://147.79.87.94:8011
      

    
    depends_on:
      db:
        condition: service_healthy

  # 3. FRONTEND CLIENT
  frontend:
    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://147.79.87.94:8010/api
    container_name: global_dashboard_client_pro
    restart: always
    ports:
      - "8011:8011"
    environment:
      # Variable para el servidor en tiempo de ejecución
      - NEXT_PUBLIC_API_URL=http://147.79.87.94:8010/api
    depends_on:
      - backend

volumes:
  pgdata_pro: